version: '2'
services:
  
  openbills-soap:
    build:
      context: ./openbills/
      dockerfile: ./Dockerfile
    ports:
      - "99:8080"
    depends_on:
     - pg-alpine-eleicoes
  
  node-csv-importer:
    build:
      context: ./node-csv-importer/
      dockerfile: ./Dockerfile
    volumes:
      - ./cache/:/usr/src/app/cache
      - ./temp/:/usr/src/app/downloads
  

  pg-alpine-eleicoes:
    build:
      context: ./postgres_alpine
      dockerfile: ./Dockerfile
    ports:
      - "2345:5432" # Bind host port 5432 to PostgreSQL port 5432
    

  node-client:
    build:
      context: ./node-client
      dockerfile: ./Dockerfile
    ports:
      - "80:3000"
    links:
      - openbills-soap


  mongo:
    build:
      context: ./mongo-container
      dockerfile: ./Dockerfile
    
    volumes:
      - ./cache/:/usr/src/app/cache
      - ./temp/:/usr/src/app/downloads

    ports:
      - "270:27017"

  neo4j:
    image: thetallgrassnet/alpine-neo4j
    ports:
      - "7474:7474"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./cache/neo4j/:/data
  
  
  neo4j-importer:
    build:
      context: ./neo4j-importer
      dockerfile: ./Dockerfile
    volumes:
      - ./cache/:/usr/src/app/cache
