/*estilo 2004 create table if not exists receita_candidato(

	SEQUENCIAL_CANDIDATO serial,
	NOME_CANDIDATO varchar(200),
	DESCRICAO_CARGO varchar(20),
	CODIGO_CARGO int,
	NUMERO_CANDIDATO int,
	UNIDADE_ELEITORAL_CANDIDATO varchar(2),
	NOME_MUNICIPIO varchar(200),
	CODIGO_MUNICIPIO int,
	NUMERO_PARTIDO int, 
	SIGLA_PARTIDO varchar(10),
	VALOR_RECEITA float,
	DATA_RECEITA date,
	TIPO_RECEITA varchar(200),
	CODIGO_TIPO_RECEITA  varchar(20),
	DESCRICAO_TIPO_RECURSO varchar(20),
	CODIGO_TIPO_RECURSO int,
	NOME_DOADOR varchar(200),
	NUMERO_CPF_CGC_DOADOR  varchar(11),
	SITUACAO_CADASTRAL varchar(20),

	primary key (SEQUENCIAL_CANDIDATO)

);*/

/* estilo 2002 */
create table if not exists receita_candidato(
	SEQUENCIAL_CANDIDATO int, 
	SG_UF varchar(2),
	SG_PART varchar(10),
	DS_CARGO varchar(20),
	NO_CAND varchar(200),
	NR_CAND varchar(10),
	DT_RECEITA date,
	CD_CPF_CGC varchar(20),
	SG_UF_DOADOR varchar(2),
	NO_DOADOR varchar(200),
	VR_RECEITA float,
	TP_RECURSO varchar(20)

);

create table if not exists BEM_CANDIDATO(
	DATA_GERACAO varchar(50),
	HORA_GERACAO varchar(50),
	ANO_ELEICAO varchar(50),
	DESCRICAO_ELEICAO varchar(200),
	SIGLA_UF varchar(50),
	SQ_CANDIDATO varchar(50),
	CD_TIPO_BEM_CANDIDATO varchar(200),
	DS_TIPO_BEM_CANDIDATO varchar(200),
	DETALHE_BEM varchar(200),
	VALOR_BEM float,
	DATA_ULTIMA_ATUALIZACAO varchar(50),
	HORA_ULTIMA_ATUALIZACAO varchar(50)
);


create table if not exists CONSULTA_CAND(
	DATA_GERACAO varchar(200),
	HORA_GERACAO varchar(200),
	ANO_ELEICAO varchar(200),
	NUM_TURNO varchar(200),
	DESCRICAO_ELEICAO varchar(200),
	SIGLA_UF varchar(200),
	SIGLA_UE varchar(200),
	DESCRICAO_UE varchar(200),
	CODIGO_CARGO varchar(200),
	DESCRICAO_CARGO varchar(200),
	NOME_CANDIDATO varchar(200),
	SEQUENCIAL_CANDIDATO varchar(200),
	NUMERO_CANDIDATO varchar(200),
	CPF_CANDIDATO varchar(200),
	NOME_URNA_CANDIDATO varchar(200),
	COD_SITUACAO_CANDIDATURA int,
	DES_SITUACAO_CANDIDATURA varchar(200),
	NUMERO_PARTIDO int,
	SIGLA_PARTIDO varchar(200),
	NOME_PARTIDO varchar(200),
	CODIGO_LEGENDA varchar(200),
	SIGLA_LEGENDA varchar(200),
	COMPOSICAO_LEGENDA varchar(200),
	NOME_LEGENDA varchar(200),
	CODIGO_OCUPACAO varchar(200),
	DESCRICAO_OCUPACAO varchar(200),
	DATA_NASCIMENTO varchar(200),
	NUM_TITULO_ELEITORAL_CANDIDATO varchar(200),
	IDADE_DATA_ELEICAO varchar(200),
	CODIGO_SEXO varchar(200),
	DESCRICAO_SEXO varchar(200),
	COD_GRAU_INSTRUCAO int,
	DESCRICAO_GRAU_INSTRUCAO varchar(200),
	CODIGO_ESTADO_CIVIL varchar(200),
	DESCRICAO_ESTADO_CIVIL varchar(200),
	CODIGO_NACIONALIDADE varchar(200),
	DESCRICAO_NACIONALIDADE varchar(200),
	SIGLA_UF_NASCIMENTO varchar(200),
	CODIGO_MUNICIPIO_NASCIMENTO varchar(200),
	NOME_MUNICIPIO_NASCIMENTO varchar(200),
	DESPESA_MAX_CAMPANHA float,
	COD_SIT_TOT_TURNO int,
	DESC_SIT_TOT_TURNO varchar(200)
);